<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('country_codes', function (Blueprint $table) {
            $table->string('id', 3)->primary();
            $table->string('code', 2)->unique();
            $table->string('name');
        });

        $this->insertData();
    }

    public function insertData(): void
    {
        $countries = [
            ['id' => '004', 'name' => 'Afghanistan', 'code' => 'AF'],
            ['id' => '248', 'name' => 'Åland Islands', 'code' => 'AX'],
            ['id' => '008', 'name' => 'Albania', 'code' => 'AL'],
            ['id' => '012', 'name' => 'Algeria', 'code' => 'DZ'],
            ['id' => '016', 'name' => 'American Samoa', 'code' => 'AS'],
            ['id' => '020', 'name' => 'Andorra', 'code' => 'AD'],
            ['id' => '024', 'name' => 'Angola', 'code' => 'AO'],
            ['id' => '660', 'name' => 'Anguilla', 'code' => 'AI'],
            ['id' => '010', 'name' => 'Antarctica', 'code' => 'AQ'],
            ['id' => '028', 'name' => 'Antigua and Barbuda', 'code' => 'AG'],
            ['id' => '032', 'name' => 'Argentina', 'code' => 'AR'],
            ['id' => '051', 'name' => 'Armenia', 'code' => 'AM'],
            ['id' => '533', 'name' => 'Aruba', 'code' => 'AW'],
            ['id' => '036', 'name' => 'Australia', 'code' => 'AU'],
            ['id' => '040', 'name' => 'Austria', 'code' => 'AT'],
            ['id' => '031', 'name' => 'Azerbaijan', 'code' => 'AZ'],
            ['id' => '044', 'name' => 'Bahamas', 'code' => 'BS'],
            ['id' => '048', 'name' => 'Bahrain', 'code' => 'BH'],
            ['id' => '050', 'name' => 'Bangladesh', 'code' => 'BD'],
            ['id' => '052', 'name' => 'Barbados', 'code' => 'BB'],
            ['id' => '112', 'name' => 'Belarus', 'code' => 'BY'],
            ['id' => '056', 'name' => 'Belgium', 'code' => 'BE'],
            ['id' => '084', 'name' => 'Belize', 'code' => 'BZ'],
            ['id' => '204', 'name' => 'Benin', 'code' => 'BJ'],
            ['id' => '060', 'name' => 'Bermuda', 'code' => 'BM'],
            ['id' => '064', 'name' => 'Bhutan', 'code' => 'BT'],
            ['id' => '068', 'name' => 'Bolivia (Plurinational State of)', 'code' => 'BO'],
            ['id' => '535', 'name' => 'Bonaire, Sint Eustatius and Saba', 'code' => 'BQ'],
            ['id' => '070', 'name' => 'Bosnia and Herzegovina', 'code' => 'BA'],
            ['id' => '072', 'name' => 'Botswana', 'code' => 'BW'],
            ['id' => '074', 'name' => 'Bouvet Island', 'code' => 'BV'],
            ['id' => '076', 'name' => 'Brazil', 'code' => 'BR'],
            ['id' => '086', 'name' => 'British Indian Ocean Territory', 'code' => 'IO'],
            ['id' => '096', 'name' => 'Brunei Darussalam', 'code' => 'BN'],
            ['id' => '100', 'name' => 'Bulgaria', 'code' => 'BG'],
            ['id' => '854', 'name' => 'Burkina Faso', 'code' => 'BF'],
            ['id' => '108', 'name' => 'Burundi', 'code' => 'BI'],
            ['id' => '132', 'name' => 'Cabo Verde', 'code' => 'CV'],
            ['id' => '116', 'name' => 'Cambodia', 'code' => 'KH'],
            ['id' => '120', 'name' => 'Cameroon', 'code' => 'CM'],
            ['id' => '124', 'name' => 'Canada', 'code' => 'CA'],
            ['id' => '136', 'name' => 'Cayman Islands', 'code' => 'KY'],
            ['id' => '140', 'name' => 'Central African Republic', 'code' => 'CF'],
            ['id' => '148', 'name' => 'Chad', 'code' => 'TD'],
            ['id' => '152', 'name' => 'Chile', 'code' => 'CL'],
            ['id' => '156', 'name' => 'China', 'code' => 'CN'],
            ['id' => '162', 'name' => 'Christmas Island', 'code' => 'CX'],
            ['id' => '166', 'name' => 'Cocos (Keeling) Islands', 'code' => 'CC'],
            ['id' => '170', 'name' => 'Colombia', 'code' => 'CO'],
            ['id' => '174', 'name' => 'Comoros', 'code' => 'KM'],
            ['id' => '180', 'name' => 'Congo (Democratic Republic of the)', 'code' => 'CD'],
            ['id' => '178', 'name' => 'Congo', 'code' => 'CG'],
            ['id' => '184', 'name' => 'Cook Islands', 'code' => 'CK'],
            ['id' => '188', 'name' => 'Costa Rica', 'code' => 'CR'],
            ['id' => '384', 'name' => "Côte d'Ivoire", 'code' => 'CI'],
            ['id' => '191', 'name' => 'Croatia', 'code' => 'HR'],
            ['id' => '192', 'name' => 'Cuba', 'code' => 'CU'],
            ['id' => '531', 'name' => 'Curaçao', 'code' => 'CW'],
            ['id' => '196', 'name' => 'Cyprus', 'code' => 'CY'],
            ['id' => '203', 'name' => 'Czechia', 'code' => 'CZ'],
            ['id' => '208', 'name' => 'Denmark', 'code' => 'DK'],
            ['id' => '262', 'name' => 'Djibouti', 'code' => 'DJ'],
            ['id' => '212', 'name' => 'Dominica', 'code' => 'DM'],
            ['id' => '214', 'name' => 'Dominican Republic', 'code' => 'DO'],
            ['id' => '218', 'name' => 'Ecuador', 'code' => 'EC'],
            ['id' => '818', 'name' => 'Egypt', 'code' => 'EG'],
            ['id' => '222', 'name' => 'El Salvador', 'code' => 'SV'],
            ['id' => '226', 'name' => 'Equatorial Guinea', 'code' => 'GQ'],
            ['id' => '232', 'name' => 'Eritrea', 'code' => 'ER'],
            ['id' => '233', 'name' => 'Estonia', 'code' => 'EE'],
            ['id' => '748', 'name' => 'Eswatini', 'code' => 'SZ'],
            ['id' => '231', 'name' => 'Ethiopia', 'code' => 'ET'],
            ['id' => '238', 'name' => 'Falkland Islands (Malvinas)', 'code' => 'FK'],
            ['id' => '234', 'name' => 'Faroe Islands', 'code' => 'FO'],
            ['id' => '242', 'name' => 'Fiji', 'code' => 'FJ'],
            ['id' => '246', 'name' => 'Finland', 'code' => 'FI'],
            ['id' => '250', 'name' => 'France', 'code' => 'FR'],
            ['id' => '254', 'name' => 'French Guiana', 'code' => 'GF'],
            ['id' => '258', 'name' => 'French Polynesia', 'code' => 'PF'],
            ['id' => '260', 'name' => 'French Southern Territories', 'code' => 'TF'],
            ['id' => '266', 'name' => 'Gabon', 'code' => 'GA'],
            ['id' => '270', 'name' => 'Gambia', 'code' => 'GM'],
            ['id' => '268', 'name' => 'Georgia', 'code' => 'GE'],
            ['id' => '276', 'name' => 'Germany', 'code' => 'DE'],
            ['id' => '288', 'name' => 'Ghana', 'code' => 'GH'],
            ['id' => '292', 'name' => 'Gibraltar', 'code' => 'GI'],
            ['id' => '300', 'name' => 'Greece', 'code' => 'GR'],
            ['id' => '304', 'name' => 'Greenland', 'code' => 'GL'],
            ['id' => '308', 'name' => 'Grenada', 'code' => 'GD'],
            ['id' => '312', 'name' => 'Guadeloupe', 'code' => 'GP'],
            ['id' => '316', 'name' => 'Guam', 'code' => 'GU'],
            ['id' => '320', 'name' => 'Guatemala', 'code' => 'GT'],
            ['id' => '831', 'name' => 'Guernsey', 'code' => 'GG'],
            ['id' => '324', 'name' => 'Guinea', 'code' => 'GN'],
            ['id' => '624', 'name' => 'Guinea-Bissau', 'code' => 'GW'],
            ['id' => '328', 'name' => 'Guyana', 'code' => 'GY'],
            ['id' => '332', 'name' => 'Haiti', 'code' => 'HT'],
            ['id' => '334', 'name' => 'Heard Island and McDonald Islands', 'code' => 'HM'],
            ['id' => '336', 'name' => 'Holy See', 'code' => 'VA'],
            ['id' => '340', 'name' => 'Honduras', 'code' => 'HN'],
            ['id' => '344', 'name' => 'Hong Kong', 'code' => 'HK'],
            ['id' => '348', 'name' => 'Hungary', 'code' => 'HU'],
            ['id' => '352', 'name' => 'Iceland', 'code' => 'IS'],
            ['id' => '356', 'name' => 'India', 'code' => 'IN'],
            ['id' => '360', 'name' => 'Indonesia', 'code' => 'ID'],
            ['id' => '364', 'name' => 'Iran (Islamic Republic of)', 'code' => 'IR'],
            ['id' => '368', 'name' => 'Iraq', 'code' => 'IQ'],
            ['id' => '372', 'name' => 'Ireland', 'code' => 'IE'],
            ['id' => '833', 'name' => 'Isle of Man', 'code' => 'IM'],
            ['id' => '376', 'name' => 'Israel', 'code' => 'IL'],
            ['id' => '380', 'name' => 'Italy', 'code' => 'IT'],
            ['id' => '388', 'name' => 'Jamaica', 'code' => 'JM'],
            ['id' => '392', 'name' => 'Japan', 'code' => 'JP'],
            ['id' => '832', 'name' => 'Jersey', 'code' => 'JE'],
            ['id' => '400', 'name' => 'Jordan', 'code' => 'JO'],
            ['id' => '398', 'name' => 'Kazakhstan', 'code' => 'KZ'],
            ['id' => '404', 'name' => 'Kenya', 'code' => 'KE'],
            ['id' => '296', 'name' => 'Kiribati', 'code' => 'KI'],
            ['id' => '408', 'name' => "Korea (Democratic People's Republic of)", 'code' => 'KP'],
            ['id' => '410', 'name' => 'Korea, Republic of', 'code' => 'KR'],
            ['id' => '414', 'name' => 'Kuwait', 'code' => 'KW'],
            ['id' => '417', 'name' => 'Kyrgyzstan', 'code' => 'KG'],
            ['id' => '418', 'name' => "Lao People's Democratic Republic", 'code' => 'LA'],
            ['id' => '428', 'name' => 'Latvia', 'code' => 'LV'],
            ['id' => '422', 'name' => 'Lebanon', 'code' => 'LB'],
            ['id' => '426', 'name' => 'Lesotho', 'code' => 'LS'],
            ['id' => '430', 'name' => 'Liberia', 'code' => 'LR'],
            ['id' => '434', 'name' => 'Libya', 'code' => 'LY'],
            ['id' => '438', 'name' => 'Liechtenstein', 'code' => 'LI'],
            ['id' => '440', 'name' => 'Lithuania', 'code' => 'LT'],
            ['id' => '442', 'name' => 'Luxembourg', 'code' => 'LU'],
            ['id' => '446', 'name' => 'Macao', 'code' => 'MO'],
            ['id' => '450', 'name' => 'Madagascar', 'code' => 'MG'],
            ['id' => '454', 'name' => 'Malawi', 'code' => 'MW'],
            ['id' => '458', 'name' => 'Malaysia', 'code' => 'MY'],
            ['id' => '462', 'name' => 'Maldives', 'code' => 'MV'],
            ['id' => '466', 'name' => 'Mali', 'code' => 'ML'],
            ['id' => '470', 'name' => 'Malta', 'code' => 'MT'],
            ['id' => '584', 'name' => 'Marshall Islands', 'code' => 'MH'],
            ['id' => '474', 'name' => 'Martinique', 'code' => 'MQ'],
            ['id' => '478', 'name' => 'Mauritania', 'code' => 'MR'],
            ['id' => '480', 'name' => 'Mauritius', 'code' => 'MU'],
            ['id' => '175', 'name' => 'Mayotte', 'code' => 'YT'],
            ['id' => '484', 'name' => 'Mexico', 'code' => 'MX'],
            ['id' => '583', 'name' => 'Micronesia (Federated States of)', 'code' => 'FM'],
            ['id' => '498', 'name' => 'Moldova, Republic of', 'code' => 'MD'],
            ['id' => '492', 'name' => 'Monaco', 'code' => 'MC'],
            ['id' => '496', 'name' => 'Mongolia', 'code' => 'MN'],
            ['id' => '499', 'name' => 'Montenegro', 'code' => 'ME'],
            ['id' => '500', 'name' => 'Montserrat', 'code' => 'MS'],
            ['id' => '504', 'name' => 'Morocco', 'code' => 'MA'],
            ['id' => '508', 'name' => 'Mozambique', 'code' => 'MZ'],
            ['id' => '104', 'name' => 'Myanmar', 'code' => 'MM'],
            ['id' => '516', 'name' => 'Namibia', 'code' => 'NA'],
            ['id' => '520', 'name' => 'Nauru', 'code' => 'NR'],
            ['id' => '524', 'name' => 'Nepal', 'code' => 'NP'],
            ['id' => '528', 'name' => 'Netherlands', 'code' => 'NL'],
            ['id' => '540', 'name' => 'New Caledonia', 'code' => 'NC'],
            ['id' => '554', 'name' => 'New Zealand', 'code' => 'NZ'],
            ['id' => '558', 'name' => 'Nicaragua', 'code' => 'NI'],
            ['id' => '562', 'name' => 'Niger', 'code' => 'NE'],
            ['id' => '566', 'name' => 'Nigeria', 'code' => 'NG'],
            ['id' => '570', 'name' => 'Niue', 'code' => 'NU'],
            ['id' => '574', 'name' => 'Norfolk Island', 'code' => 'NF'],
            ['id' => '807', 'name' => 'North Macedonia', 'code' => 'MK'],
            ['id' => '580', 'name' => 'Northern Mariana Islands', 'code' => 'MP'],
            ['id' => '578', 'name' => 'Norway', 'code' => 'NO'],
            ['id' => '512', 'name' => 'Oman', 'code' => 'OM'],
            ['id' => '586', 'name' => 'Pakistan', 'code' => 'PK'],
            ['id' => '585', 'name' => 'Palau', 'code' => 'PW'],
            ['id' => '275', 'name' => 'Palestine, State of', 'code' => 'PS'],
            ['id' => '591', 'name' => 'Panama', 'code' => 'PA'],
            ['id' => '598', 'name' => 'Papua New Guinea', 'code' => 'PG'],
            ['id' => '600', 'name' => 'Paraguay', 'code' => 'PY'],
            ['id' => '604', 'name' => 'Peru', 'code' => 'PE'],
            ['id' => '608', 'name' => 'Philippines', 'code' => 'PH'],
            ['id' => '612', 'name' => 'Pitcairn', 'code' => 'PN'],
            ['id' => '616', 'name' => 'Poland', 'code' => 'PL'],
            ['id' => '620', 'name' => 'Portugal', 'code' => 'PT'],
            ['id' => '630', 'name' => 'Puerto Rico', 'code' => 'PR'],
            ['id' => '634', 'name' => 'Qatar', 'code' => 'QA'],
            ['id' => '638', 'name' => 'Réunion', 'code' => 'RE'],
            ['id' => '642', 'name' => 'Romania', 'code' => 'RO'],
            ['id' => '643', 'name' => 'Russian Federation', 'code' => 'RU'],
            ['id' => '646', 'name' => 'Rwanda', 'code' => 'RW'],
            ['id' => '652', 'name' => 'Saint Barthélemy', 'code' => 'BL'],
            ['id' => '654', 'name' => 'Saint Helena, Ascension and Tristan da Cunha', 'code' => 'SH'],
            ['id' => '659', 'name' => 'Saint Kitts and Nevis', 'code' => 'KN'],
            ['id' => '662', 'name' => 'Saint Lucia', 'code' => 'LC'],
            ['id' => '663', 'name' => 'Saint Martin (French part)', 'code' => 'MF'],
            ['id' => '666', 'name' => 'Saint Pierre and Miquelon', 'code' => 'PM'],
            ['id' => '670', 'name' => 'Saint Vincent and the Grenadines', 'code' => 'VC'],
            ['id' => '882', 'name' => 'Samoa', 'code' => 'WS'],
            ['id' => '674', 'name' => 'San Marino', 'code' => 'SM'],
            ['id' => '678', 'name' => 'Sao Tome and Principe', 'code' => 'ST'],
            ['id' => '682', 'name' => 'Saudi Arabia', 'code' => 'SA'],
            ['id' => '686', 'name' => 'Senegal', 'code' => 'SN'],
            ['id' => '688', 'name' => 'Serbia', 'code' => 'RS'],
            ['id' => '690', 'name' => 'Seychelles', 'code' => 'SC'],
            ['id' => '694', 'name' => 'Sierra Leone', 'code' => 'SL'],
            ['id' => '702', 'name' => 'Singapore', 'code' => 'SG'],
            ['id' => '534', 'name' => 'Sint Maarten (Dutch part)', 'code' => 'SX'],
            ['id' => '703', 'name' => 'Slovakia', 'code' => 'SK'],
            ['id' => '705', 'name' => 'Slovenia', 'code' => 'SI'],
            ['id' => '090', 'name' => 'Solomon Islands', 'code' => 'SB'],
            ['id' => '706', 'name' => 'Somalia', 'code' => 'SO'],
            ['id' => '710', 'name' => 'South Africa', 'code' => 'ZA'],
            ['id' => '239', 'name' => 'South Georgia and the South Sandwich Islands', 'code' => 'GS'],
            ['id' => '728', 'name' => 'South Sudan', 'code' => 'SS'],
            ['id' => '724', 'name' => 'Spain', 'code' => 'ES'],
            ['id' => '144', 'name' => 'Sri Lanka', 'code' => 'LK'],
            ['id' => '729', 'name' => 'Sudan', 'code' => 'SD'],
            ['id' => '740', 'name' => 'Suriname', 'code' => 'SR'],
            ['id' => '744', 'name' => 'Svalbard and Jan Mayen', 'code' => 'SJ'],
            ['id' => '752', 'name' => 'Sweden', 'code' => 'SE'],
            ['id' => '756', 'name' => 'Switzerland', 'code' => 'CH'],
            ['id' => '760', 'name' => 'Syrian Arab Republic', 'code' => 'SY'],
            ['id' => '158', 'name' => 'Taiwan, Province of China', 'code' => 'TW'],
            ['id' => '762', 'name' => 'Tajikistan', 'code' => 'TJ'],
            ['id' => '834', 'name' => 'Tanzania, United Republic of', 'code' => 'TZ'],
            ['id' => '764', 'name' => 'Thailand', 'code' => 'TH'],
            ['id' => '626', 'name' => 'Timor-Leste', 'code' => 'TL'],
            ['id' => '768', 'name' => 'Togo', 'code' => 'TG'],
            ['id' => '772', 'name' => 'Tokelau', 'code' => 'TK'],
            ['id' => '776', 'name' => 'Tonga', 'code' => 'TO'],
            ['id' => '780', 'name' => 'Trinidad and Tobago', 'code' => 'TT'],
            ['id' => '788', 'name' => 'Tunisia', 'code' => 'TN'],
            ['id' => '792', 'name' => 'Türkiye', 'code' => 'TR'],
            ['id' => '795', 'name' => 'Turkmenistan', 'code' => 'TM'],
            ['id' => '796', 'name' => 'Turks and Caicos Islands', 'code' => 'TC'],
            ['id' => '798', 'name' => 'Tuvalu', 'code' => 'TV'],
            ['id' => '800', 'name' => 'Uganda', 'code' => 'UG'],
            ['id' => '804', 'name' => 'Ukraine', 'code' => 'UA'],
            ['id' => '784', 'name' => 'United Arab Emirates', 'code' => 'AE'],
            ['id' => '826', 'name' => 'United Kingdom of Great Britain and Northern Ireland', 'code' => 'GB'],
            ['id' => '840', 'name' => 'United States of America', 'code' => 'US'],
            ['id' => '581', 'name' => 'United States Minor Outlying Islands', 'code' => 'UM'],
            ['id' => '858', 'name' => 'Uruguay', 'code' => 'UY'],
            ['id' => '860', 'name' => 'Uzbekistan', 'code' => 'UZ'],
            ['id' => '548', 'name' => 'Vanuatu', 'code' => 'VU'],
            ['id' => '862', 'name' => 'Venezuela (Bolivarian Republic of)', 'code' => 'VE'],
            ['id' => '704', 'name' => 'Viet Nam', 'code' => 'VN'],
            ['id' => '092', 'name' => 'Virgin Islands (British)', 'code' => 'VG'],
            ['id' => '850', 'name' => 'Virgin Islands (U.S.)', 'code' => 'VI'],
            ['id' => '876', 'name' => 'Wallis and Futuna', 'code' => 'WF'],
            ['id' => '732', 'name' => 'Western Sahara', 'code' => 'EH'],
            ['id' => '887', 'name' => 'Yemen', 'code' => 'YE'],
            ['id' => '894', 'name' => 'Zambia', 'code' => 'ZM'],
            ['id' => '716', 'name' => 'Zimbabwe', 'code' => 'ZW'],
        ];

        DB::table('country_codes')->insert($countries);
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('country_codes');
    }
};
